/**
 * Settings constants
 */
export const FETCH_NOTIFICATIONS_SETTINGS_START =
  '[Settings] FETCH_NOTIFICATIONS_SETTINGS_START';
export const FETCH_NOTIFICATIONS_SETTINGS_FAIL =
  '[Settings] FETCH_NOTIFICATIONS_SETTINGS_FAIL';
export const SET_NOTIFICATIONS_SETTINGS =
  '[Settings] SET_NOTIFICATIONS_SETTINGS';
export const SET_NOTIFICATION_PREFERENCES =
  '[Settings] SET_NOTIFICATION_PREFERENCES';
export const SET_NOTIFICATION_PREFERENCES_START =
  '[Settings] SET_NOTIFICATION_PREFERENCES_START';
export const SET_NOTIFICATION_PREFERENCES_FAIL =
  '[Settings SET_NOTIFICATION_PREFERENCES_FAIL';
export const SET_UNIT_MEASUREMENT_START =
  '[Settings] SET_UNIT_MEASUREMENT_START';
export const SET_UNIT_MEASUREMENT = '[Settings] SET_UNIT_MEASUREMENT';
export const SET_UNIT_MEASUREMENT_FAIL = '[Settings] SET_UNIT_MEASUREMENT_FAIL';
